name: Go Build and Test

on:
  push:
    tags:
      - 'v*'  # Run workflow on version tags, e.g. v1.0.0
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Removed windows-latest
        go: ['1.23', '1.x']

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        
    - name: Build
      run: |
        cd rt-tui
        go build -v -o rotten
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: rotten-${{ matrix.os }}-go${{ matrix.go }}
        path: rt-tui/rotten
        if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed for creating releases
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      # Simplified release preparation - just Linux and macOS
      - name: Prepare release artifacts
        run: |
          mkdir -p release-artifacts
          
          # Linux build
          if [ -d "artifacts/rotten-ubuntu-latest-go1.x" ]; then
            cp artifacts/rotten-ubuntu-latest-go1.x/rotten release-artifacts/rotten-linux
            chmod +x release-artifacts/rotten-linux
            echo "Linux binary prepared"
          fi
          
          # macOS build
          if [ -d "artifacts/rotten-macos-latest-go1.x" ]; then
            cp artifacts/rotten-macos-latest-go1.x/rotten release-artifacts/rotten-macos
            chmod +x release-artifacts/rotten-macos
            echo "macOS binary prepared"
          fi
          
          # List files for verification
          echo "Files ready for release:"
          ls -la release-artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/*
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ github.token }}