name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.18', '1.x']

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: |
        cd rt-tui
        go build -v -o rotten

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: rotten-${{ matrix.os }}
        path: rt-tui/rotten*
        if-no-files-found: error